# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseOperation',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfinance.Expense')),
            ],
        ),
        migrations.CreateModel(
            name='Ingress',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='IngressOperation',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('operation_date', models.DateField(blank=True, null=True)),
                ('account', models.CharField(blank=True, max_length=40, null=True)),
                ('ingress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webfinance.Ingress')),
            ],
        ),
    ]
